name: counter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9 # Riverpod 상태 관리
  riverpod_annotation: ^2.3.3 # 코드 생성 어노테이션
  go_router: ^14.6.2 # 라우팅

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.9 # Riverpod 코드 생성기
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
